Feature EPL-1695: Fix Jenkinsfile postgres connection error.

diff --git a/pipelines/Jenkinsfile b/pipelines/Jenkinsfile
--- a/pipelines/Jenkinsfile
+++ b/pipelines/Jenkinsfile
@@ -22,12 +22,13 @@ pipeline {
     COMMIT_AUTHOR_NAME  = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
     COMMIT_AUTHOR_EMAIL = sh(returnStdout: true, script: "git log -1 --pretty=format:'%ae'").trim()
 
-    ETENDO_CORE_URL   = 'https://github.com/etendosoftware/etendo_core'
+    ETENDO_BASE_URL   = 'https://github.com/etendosoftware/etendo_base'
     DOCKER_MODULE_URL = 'https://github.com/etendosoftware/com.etendoerp.docker'
 
     TOMCAT_URL      = 'https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz'
     JAVA_HOME       = '/usr/lib/jvm/java-11-openjdk-amd64'
     MODULE_PACKAGE  = 'com.etendoerp.docker'
+    ETENDO_BASE     = 'etendo_base'
 
     COMMIT_INPROGRESS_STATUS = 'pending'
     COMMIT_SUCCESS_STATUS    = 'success'
@@ -42,11 +43,11 @@ pipeline {
     MAIN_BRANCH          = "main"
   }
 
-  agent {
+  agent { // MARK: - Agent
     kubernetes {
-        inheritFrom 'jenkins-node-pg'
-        defaultContainer 'jnlp'
-        yaml """
+      inheritFrom 'jenkins-node-rx'
+      defaultContainer 'jnlp'
+      yaml """
 apiVersion: v1
 kind: Pod
 metadata:
@@ -55,7 +56,6 @@ metadata:
   labels:
     app.kubernetes.io/name: jenkins-node-pg
 spec:
-  hostNetwork: true
   volumes:
     - name: rsa-keys
       configMap:
@@ -117,30 +117,27 @@ spec:
           script {
             sh "./pipelines/utils/build-update.sh ${MODULE_PACKAGE} ${COMMIT_INPROGRESS_STATUS} \"Starting build\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
             try {
-              echo '---------------- Print environment ----------------'
-              sh 'printenv'
-
-              echo '---------------- Choice of etendo_core branch ----------------'
+              echo '---------------- Choice of etendo_base branch ----------------'
               env.BASE_BRANCH = env.MAIN_BRANCH
               if (env.GIT_BRANCH.contains("-Y") || env.GIT_BRANCH.startsWith("release")) {
                   env.BASE_BRANCH = env.BASE_BRANCH_BACKPORT
               }
 
               echo '--------------- Building Etendo environment ----------------'
-              sh "git clone ${ETENDO_CORE_URL}"
+              sh "git clone ${ETENDO_BASE_URL}"
 
               echo "--------------- Building Etendo environment ----------------"
 
-              sh "wget -O apache-tomcat.tar.gz $TOMCAT_URL"
-              sh "tar -xvf apache-tomcat.tar.gz -C $WORKSPACE"
+              sh "wget -O apache-tomcat.tar.gz ${TOMCAT_URL}"
+              sh "tar -xvf apache-tomcat.tar.gz -C ${WORKSPACE} > /dev/null 2>&1"
 
               env.TOMCAT_FOLDER = sh(script: "basename ${TOMCAT_URL} .tar.gz", returnStdout: true).trim()
               env.CATALINA_HOME = "${WORKSPACE}/${TOMCAT_FOLDER}"
               env.CATALINA_BASE = "${WORKSPACE}/${TOMCAT_FOLDER}"
 
               sh """
-              cd etendo_core
-              git checkout ${BASE_BRANCH}
+              cd ${ETENDO_BASE}
+              git checkout main
 
               echo "\n
               context.name=${CONTEXT_NAME}
@@ -158,6 +155,7 @@ spec:
               org.gradle.vfs.watch=false
               docker_com.etendoerp.docker_db=true
               org.gradle.jvmargs=-Dfile.encoding=UTF-8
+              org.gradle.daemon=false
               java.version=11" > gradle.properties
               """
 
@@ -167,67 +165,45 @@ spec:
                 dependencies {
                     implementation(\"com.etendoerp.platform:etendo-core:[24.4.0,${NEXT_CLASSIC_VERSION})\")
                 }
-
-                etendo {
-                  ignoreCoreJarDependency = true
-                }
               """
-
               sh """
-              cd etendo_core
+              cd ${ETENDO_BASE}
               echo '${buildGradleContent}' >> build.gradle
-              cat build.gradle
               """
-              
               echo '---------------- Build & Compile ----------------'
               sh "./pipelines/utils/build-update.sh ${MODULE_PACKAGE} ${COMMIT_INPROGRESS_STATUS} \"Starting test stage\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
-
-              sh '''
-                cd etendo_core
+              sh """
+                cd ${ETENDO_BASE}
                 mkdir -p modules
                 cd modules
                 git clone ${DOCKER_MODULE_URL}.git
-                cd ${MODULE_PACKAGE}/compose
-
-                # 1) Quito la sección de networks:
-                sed -i '/^[[:space:]]*networks:/,+1d' com.etendoerp.docker_db.yml
-
-                # 2) Quito la sección de ports:
-                sed -i '/^[[:space:]]*ports:/,+1d' com.etendoerp.docker_db.yml
-
-                # 3) Inserto network_mode con indentación correcta
-                awk '
-                /^[[:space:]]*image: postgres:16/ {
-                  print
-                  print "    network_mode: host"
-                  next
-                }
-                { print }
-                ' com.etendoerp.docker_db.yml > tmp.yml && mv tmp.yml com.etendoerp.docker_db.yml
-
-                # 4) Verifico el resultado
-                cat com.etendoerp.docker_db.yml
-              '''
-
-
-              sh """
-                cd etendo_core
+                cd ${MODULE_PACKAGE}
+                git checkout ${GIT_COMMIT}
+                cd ../..
                 ./gradlew prepareConfig
                 ./gradlew setup
-                ./gradlew resources.up -Pcontext.name=${CONTEXT_NAME}
+                ./gradlew resources.up --info
               """
-              sh '''
-                echo "=== Contenedores Postgres ==="
-                docker ps --filter name=etendo-db --format "{{.Names}}\t{{.Status}}"
-                sleep 30s
-                echo "=== Prueba de conexión ==="
-                psql -h localhost -U ${BBDD_SYSTEMUSER} -c '\\l'
-              '''
-
+              def pgIp = sh(
+                script: "docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' etendo-db-1",
+                returnStdout: true
+              ).trim()
+              def confFile = "${ETENDO_BASE}/gradle.properties"
+              sh """
+                echo Postgres IP: ${pgIp}
+                # Replace or add dbdd.url
+                if grep -q '^bbdd.url=' ${confFile}; then
+                  sed -i  "s|^bbdd.url=.*|bbdd.url=jdbc:postgresql://${pgIp}:${BBDD_PORT}|" ${confFile}
+                else
+                  echo "bbdd.url=jdbc:postgresql://${pgIp}:${BBDD_PORT}" >> ${confFile}
+                fi
+                cd ${ETENDO_BASE}
+                ./gradlew setup
+              """
 
               echo '---------------- Verifying Docker Containers ----------------'
               sleep time: 15, unit: 'SECONDS'
-              def dockerPsOutput = sh(script: 'docker ps -a', returnStdout: true)
+              def dockerPsOutput = sh(script: 'docker ps', returnStdout: true)
               echo "${dockerPsOutput}"
               if (!dockerPsOutput.contains("etendo-db-1")) {
                 error('The etendo-db-1 container is not running')
@@ -235,20 +211,44 @@ spec:
               echo "---------------- Docker Containers are running ----------------"
 
               echo "-------------------- Checking install task --------------------"
-              sh """
-              cd etendo_core
-              ./gradlew install smartbuild
+               echo "🔌 Closing active connections to the 'etendo' database"
+               sh """
+                echo '🧹 Attempting to delete the etendo database (if it exists)...'
+                PGPASSWORD=${BBDD_SYSTEMPASS} psql \"host=${pgIp} port=${BBDD_PORT} user=${BBDD_SYSTEMUSER} dbname=postgres\" -c \\
+                  \"DROP DATABASE IF EXISTS etendo WITH (FORCE);\" || echo '⚠️ Could not delete database or it did not exist. Continuing...'
+                cd ${ETENDO_BASE}
+                ./gradlew install
+                ./gradlew smartbuild
               """
               sh "${WORKSPACE}/${TOMCAT_FOLDER}/bin/catalina.sh start"
-              sh "sleep 1m"
+              def timeout = 60 // Timeout in seconds
+              def interval = 5 // Interval between checks in seconds
+              def elapsed = 0
+              def tomcatReady = false
+              def url = "http://localhost:8080/${CONTEXT_NAME}/security/Login_FS.html"
+              while (elapsed < timeout) {
+                try {
+                  tomcatResponse = sh(
+                    script: "curl -s -o /dev/null -w \"%{http_code}\" ${url}",
+                    returnStdout: true
+                  ).trim()
+                  echo "Tomcat response code: ${tomcatResponse}"
+                } catch (e) {
+                  tomcatResponse = "000"
+                }
 
-              def tomcatResponse = sh(
-                script: """
-                  curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/${CONTEXT_NAME}/security/Login_FS.html
-                """,
-                returnStdout: true
-              ).trim()
+                if (tomcatResponse == "200") {
+                  tomcatReady = true
+                  break
+                }
 
+                echo "Tomcat not ready yet. Response code: ${tomcatResponse}. Retrying in ${interval} seconds..."
+                sleep interval
+                elapsed += interval
+              }
+              if (!tomcatReady) {
+                error("Tomcat did not start within the timeout period of ${timeout} seconds.")
+              }
               echo "Tomcat response code: ${tomcatResponse}"
               if (tomcatResponse != "200") {
                 error("Tomcat did not respond with 200. Response code: ${tomcatResponse}")
@@ -257,13 +257,12 @@ spec:
               echo "-------------------- Stopping Tomcat --------------------"
               sh "${WORKSPACE}/${TOMCAT_FOLDER}/bin/catalina.sh stop"
 
-              
               sh """
-              cd etendo_core
-              ./gradlew resources.stop -Pcontext.name=${CONTEXT_NAME}
+              cd ${ETENDO_BASE}
+              ./gradlew resources.stop
               """
-              
-              sleep time: 15, unit: 'SECONDS'              
+
+              sleep time: 15, unit: 'SECONDS'
               dockerPsOutput = sh(script: 'docker ps -a', returnStdout: true)
               echo "${dockerPsOutput}"
               if (dockerPsOutput.contains("etendo-db-1") && !dockerPsOutput.contains("Exited")) {
@@ -272,11 +271,11 @@ spec:
 
               echo '---------------- Cleaning Docker Containers ----------------'
               sh """
-              cd etendo_core
-              ./gradlew resources.down -Pcontext.name=${CONTEXT_NAME}
+              cd ${ETENDO_BASE}
+              ./gradlew resources.down
               """
-              
-              sleep time: 15, unit: 'SECONDS'              
+
+              sleep time: 15, unit: 'SECONDS'
               dockerPsOutput = sh(script: 'docker ps -a', returnStdout: true)
               echo "${dockerPsOutput}"
               if (dockerPsOutput.contains("etendo-db-1")) {
@@ -286,6 +285,10 @@ spec:
               currentBuild.result = SUCCESS
             } catch (Exception e) {
               echo '---------------- Build environment Failed ----------------'
+              sh """
+                cd ${ETENDO_BASE}
+                ./gradlew resources.down
+              """
               echo "Exception occurred: " + e.toString()
               currentBuild.result = FAILED
               error('Build Failed')
@@ -295,7 +298,7 @@ spec:
       }
     }
   }
-  
+
   post {
     success {
       container('compiler') {
@@ -305,74 +308,74 @@ spec:
       }
     }
 
-//     fixed {
-//       mail to: EMAIL_ADDRESS,
-//       subject: "✅ FIXED - ${currentBuild.fullDisplayName}",
-//       mimeType: 'text/html',
-//       body: """
-//       <html>
-//           <head>
-//               <style>
-//                   body { font-family: 'Arial', sans-serif; }
-//                   .header { font-size: 16px; font-weight: bold; color: #333; }
-//               </style>
-//           </head>
-//           <body>
-//               <p><em>${new Date()}</em></p>
-//               <p>__________________________________________________________</p>
-//
-//               <h2 class="header">✅ ERRORS FIXED ✅</h2>
-//
-//               <p>
-//                   <strong>Commit:</strong> <a href="${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}">${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}</a><br />
-//                   <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
-//               </p>
-//               <p>
-//                   The build has been fixed.<br />
-//                   💡 This build was on the ${MODULE_PACKAGE} module.<br />
-//                   For more information about the run, visit:<br />
-//                   <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
-//               </p>
-//               <p>__________________________________________________________</p>
-//           </body>
-//       </html>
-//       """
-//     }
-//     failure {
-//       container('compiler') {
-//         script {
-//           sh "./pipelines/utils/build-update.sh ${MODULE_PACKAGE} ${COMMIT_FAILED_STATUS} \"Build Failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
-//         }
-//       }
-//       mail to: EMAIL_ADDRESS,
-//       subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
-//       mimeType: 'text/html',
-//       body:  """
-//       <html>
-//           <head>
-//               <style>
-//                   body { font-family: 'Arial', sans-serif; }
-//                   .header { font-size: 16px; font-weight: bold; color: #333; }
-//               </style>
-//           </head>
-//           <body>
-//               <p><em>${new Date()}</em></p>
-//               <p>__________________________________________________________</p>
-//
-//               <h2 class="header">🚫 BUILD FAILED 🚫</h2>
-//
-//               <p>
-//                   <strong>Commit:</strong> <a href="${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}">${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}</a><br />
-//                   <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
-//               </p>
-//               <p>
-//                   The build has failed unexpectedly.<br />
-//                   💡 This build was on the ${MODULE_PACKAGE} module.<br />
-//                   To more information on the failing run visit:<br />
-//                   <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
-//               </p>
-//       __________________________________________________________
-//       """
-//     }
+    fixed {
+      mail to: EMAIL_ADDRESS,
+      subject: "✅ FIXED - ${currentBuild.fullDisplayName}",
+      mimeType: 'text/html',
+      body: """
+      <html>
+          <head>
+              <style>
+                  body { font-family: 'Arial', sans-serif; }
+                  .header { font-size: 16px; font-weight: bold; color: #333; }
+              </style>
+          </head>
+          <body>
+              <p><em>${new Date()}</em></p>
+              <p>__________________________________________________________</p>
+
+              <h2 class="header">✅ ERRORS FIXED ✅</h2>
+
+              <p>
+                  <strong>Commit:</strong> <a href="${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}">${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}</a><br />
+                  <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
+              </p>
+              <p>
+                  The build has been fixed.<br />
+                  💡 This build was on the ${MODULE_PACKAGE} module.<br />
+                  For more information about the run, visit:<br />
+                  <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
+              </p>
+              <p>__________________________________________________________</p>
+          </body>
+      </html>
+      """
+    }
+    failure {
+      container('compiler') {
+        script {
+          sh "./pipelines/utils/build-update.sh ${MODULE_PACKAGE} ${COMMIT_FAILED_STATUS} \"Build Failed\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
+        }
+      }
+      mail to: EMAIL_ADDRESS,
+      subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
+      mimeType: 'text/html',
+      body:  """
+      <html>
+          <head>
+              <style>
+                  body { font-family: 'Arial', sans-serif; }
+                  .header { font-size: 16px; font-weight: bold; color: #333; }
+              </style>
+          </head>
+          <body>
+              <p><em>${new Date()}</em></p>
+              <p>__________________________________________________________</p>
+
+              <h2 class="header">🚫 BUILD FAILED 🚫</h2>
+
+              <p>
+                  <strong>Commit:</strong> <a href="${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}">${DOCKER_MODULE_URL}/commits/${env.GIT_COMMIT}</a><br />
+                  <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
+              </p>
+              <p>
+                  The build has failed unexpectedly.<br />
+                  💡 This build was on the ${MODULE_PACKAGE} module.<br />
+                  To more information on the failing run visit:<br />
+                  <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
+              </p>
+      __________________________________________________________
+      """
+    }
   }
 }
